using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ProgressBar : MonoBehaviour
{
    // Start is called before the first frame update
    public Slider timerSlider; 
    public float gameTime;
    private bool stopTimer;

    void Start()
    {
        stopTimer = false; 
        timerSlider.maxValue = gameTime; 
        timerSlider.value = gameTime; 
    }

    // Update is called once per frame
    void Update()
    {
        float time  = gameTime - Time.time; 

        int minutes = Mathf.FloorToInt(time / 60);
        int seconds = Mathf.FloorToInt(time - minutes * 60f);

        if ( time <= 0) 
        {
            stopTimer = true;
        }

        if ( stopTimer == false)
        {
            timerSlider.value = time; 
        }
    }
}
